import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.pdfgen import canvas

INDIGO = colors.HexColor("#6366f1")
LIGHT_INDIGO = colors.HexColor("#eef2ff")
RED = colors.HexColor("#dc2626")
LIGHT_RED = colors.HexColor("#fef2f2")
GREEN = colors.HexColor("#16a34a")
LIGHT_GREEN = colors.HexColor("#f0fdf4")
AMBER = colors.HexColor("#d97706")
NAVY = colors.HexColor("#1e1b4b")
LIGHT_GRAY = colors.HexColor("#f8fafc")
BORDER_GRAY = colors.HexColor("#e2e8f0")

class PDFGenerator:
    """Generates PDF reports for Talk to Data."""

    def __init__(self):
        self.styles = getSampleStyleSheet()
        
        self.styles.add(ParagraphStyle(
            name='ReportBody',
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.black
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeading',
            fontName='Helvetica-Bold',
            fontSize=14,
            textColor=INDIGO,
            spaceAfter=12,
            spaceBefore=20
        ))
        
        self.styles.add(ParagraphStyle(
            name='SubsectionHeading',
            fontName='Helvetica-Bold',
            fontSize=12,
            textColor=colors.black,
            spaceAfter=8,
            spaceBefore=16
        ))

    def _cover_page(self, canvas, doc, title, subtitle, dataset_name, row_count, tagline="Generated by Talk to Data · NatWest Hackathon"):
        """Draws the absolute cover page on the canvas directly."""
        canvas.saveState()
        canvas.setFillColor(NAVY)
        canvas.rect(0, 0, A4[0], A4[1], fill=1)
        
        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 28)
        canvas.drawString(2*cm, A4[1] - 8*cm, title)
        
        canvas.setFont("Helvetica-Oblique", 14)
        canvas.setFillColor(colors.HexColor("#cbd5e1"))
        
        paragraphs = subtitle.split('\n')
        y_pos = A4[1] - 9.5*cm
        for p in paragraphs:
             canvas.drawString(2*cm, y_pos, p)
             y_pos -= 0.8 * cm

        y_pos -= 1 * cm
        canvas.setFont("Helvetica", 12)
        canvas.setFillColor(colors.white)
        canvas.drawString(2*cm, y_pos, f"Generated on {datetime.now().strftime('%d %B %Y at %H:%M')}")
        canvas.drawString(2*cm, y_pos - 0.6*cm, f"Dataset: {dataset_name} · {row_count} rows")
        
        canvas.setStrokeColor(INDIGO)
        canvas.setLineWidth(2)
        canvas.line(2*cm, 3*cm, A4[0] - 2*cm, 3*cm)
        
        canvas.setFont("Helvetica", 10)
        canvas.setFillColor(colors.HexColor("#94a3b8"))
        canvas.drawString(2*cm, 2.2*cm, tagline)
        canvas.restoreState()

    def _add_page_number(self, canvas, doc):
        """Adds page number to subsequent pages."""
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor("#94a3b8"))
        page_num = f"Page {doc.page}"
        canvas.drawRightString(A4[0] - 2*cm, 1*cm, page_num)
        canvas.restoreState()

    def _section_heading(self, text):
        return [
            Paragraph(text, self.styles['SectionHeading']),
        ]

    def _format_currency(self, value):
        try:
            return f"£{float(value):,.2f}"
        except:
            return str(value)
            
    def _format_pct_change(self, current, previous):
        if previous == 0 or previous is None:
            return "—"
        try:
            pct = ((float(current) - float(previous)) / float(previous)) * 100
            if pct > 0:
                return f"<font color='#16a34a'>▲ +{pct:.1f}%</font>"
            elif pct < 0:
                return f"<font color='#dc2626'>▼ {pct:.1f}%</font>"
            return f"0.0%"
        except:
            return "—"

    def _data_table(self, headers, rows, highlight_col_idx=None, min_val_color=None, max_val_color=None):
        table_data = [headers] + rows
        t = Table(table_data)
        
        style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), INDIGO),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, 0), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('TOPPADDING', (0, 0), (-1, 0), 8),
            ('GRID', (0, 0), (-1, -1), 1, BORDER_GRAY),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
        ])
        
        # Right align numbers
        for i in range(len(headers)):
            if i > 0:
                style.add('ALIGN', (i, 1), (i, -1), 'RIGHT')
                style.add('ALIGN', (i, 0), (i, 0), 'RIGHT')
                
        # Alternating row colors
        for i in range(1, len(table_data)):
            if i % 2 == 0:
                style.add('BACKGROUND', (0, i), (-1, i), LIGHT_GRAY)
            else:
                style.add('BACKGROUND', (0, i), (-1, i), colors.white)
                
        t.setStyle(style)
        return t

    def _highlight_box(self, text, bg_color, border_color, bold_title=None):
        content = []
        if bold_title:
             content.append(Paragraph(f"<b>{bold_title}</b>", self.styles['ReportBody']))
             content.append(Spacer(1, 4))
        content.append(Paragraph(text, self.styles['ReportBody']))
             
        t = Table([[content]], colWidths=[A4[0] - 4*cm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), bg_color),
            ('LINELEFT', (0, 0), (0, -1), 4, border_color),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        return t
        
    def _sql_box(self, sql):
        pstyle = ParagraphStyle(
            name='SQLCode',
            fontName='Courier',
            fontSize=8,
            textColor=colors.black,
            wordWrap='CJK'
        )
        t = Table([[Paragraph(sql, pstyle)]], colWidths=[A4[0] - 4*cm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), LIGHT_GRAY),
            ('BOX', (0, 0), (-1, -1), 1, BORDER_GRAY),
            ('PADDING', (0, 0), (-1, -1), 12),
        ]))
        return t

    def _kpi_grid(self, overview):
        data = [
            [
                Paragraph(f"<font color='#6366f1' size=18><b>{self._format_currency(overview['total_revenue'])}</b></font><br/><font color='#64748b' size=9>Total Revenue</font>"),
                Paragraph(f"<font color='#6366f1' size=18><b>{overview['total_orders']:,}</b></font><br/><font color='#64748b' size=9>Total Orders</font>"),
                Paragraph(f"<font color='#6366f1' size=18><b>{overview['completed_orders']:,}</b></font><br/><font color='#64748b' size=9>Completed Orders</font>")
            ],
            [
                Paragraph(f"<font color='#6366f1' size=18><b>{overview['refund_rate']}%</b></font><br/><font color='#64748b' size=9>Refund Rate</font>"),
                Paragraph(f"<font color='#6366f1' size=18><b>{self._format_currency(overview['average_order_value'])}</b></font><br/><font color='#64748b' size=9>Avg Order Value</font>"),
                Paragraph(f"<font color='#6366f1' size=18><b>{overview['total_units_sold']:,}</b></font><br/><font color='#64748b' size=9>Units Sold</font>")
            ]
        ]
        t = Table(data, colWidths=[(A4[0] - 4*cm)/3]*3)
        t.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 20),
        ]))
        return t

    def generate_answer_report(self, report_data: dict) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
        story = []
        
        # We manually render the cover page via onFirstPage callback, so we push a "NextPageTemplate" empty block essentially
        # But wait, ReportLab SimpleDocTemplate automatically consumes the first PageBreak if we force it.
        # So we just append a PageBreak and use doc.build with callbacks.
        
        story.append(PageBreak())

        # PAGE 2
        story.extend(self._section_heading("Executive Summary"))
        story.append(Paragraph(f"<b>Question Asked:</b> {report_data.get('question', '')}", self.styles['ReportBody']))
        story.append(Spacer(1, 8))
        story.append(Paragraph(f"<b>AI Answer:</b> {report_data.get('answer', '')}", self.styles['ReportBody']))
        story.append(Spacer(1, 12))
        
        conf_label = report_data.get('confidence_label', 'High')
        conf_color = GREEN if conf_label == 'High' else (AMBER if conf_label == 'Medium' else RED)
        
        conf_table = Table([[Paragraph(f"<font color='white'>■</font>", ParagraphStyle('C', textColor=conf_color)), Paragraph(f"{conf_label} Confidence ({int(report_data.get('confidence', 0)*100)}%)", self.styles['ReportBody'])]])
        conf_table.setStyle(TableStyle([('VALIGN', (0,0), (-1,-1), 'MIDDLE')]))
        story.append(conf_table)
        story.append(Spacer(1, 16))
        
        if report_data.get('key_insight'):
            story.append(self._highlight_box(f"<b>Key Insight:</b> {report_data['key_insight']}", LIGHT_GRAY, INDIGO))
            story.append(Spacer(1, 16))
            
        if report_data.get('blocked_columns'):
            story.append(self._highlight_box(
                f"Sensitive columns automatically removed before AI processing: {', '.join(report_data['blocked_columns'])}<br/>Raw data never left the server.",
                LIGHT_RED, RED, bold_title="Data Privacy Notice"
            ))
            
        story.append(PageBreak())

        # PAGE 3
        story.extend(self._section_heading("Query Results"))
        results = report_data.get('results', [])
        if results and isinstance(results, list) and len(results) > 0:
            headers = [str(k) for k in results[0].keys()]
            rows = []
            for r in results:
                row = []
                for k in headers:
                    val = r.get(k, "")
                    if isinstance(val, (int, float)):
                        row.append(f"{val:,}")
                    else:
                        row.append(str(val))
                rows.append(row)
                
            story.append(self._data_table(headers, rows))
            story.append(Spacer(1, 8))
            story.append(Paragraph(f"<i>Showing {len(results)} rows · Query executed by Talk to Data AI</i>", ParagraphStyle('I', fontName='Helvetica-Oblique', fontSize=9, textColor=colors.gray)))
        else:
            story.append(Paragraph("No tabular results returned for this query.", self.styles['ReportBody']))
            
        story.append(PageBreak())

        # PAGE 4
        story.extend(self._section_heading("SQL Query Used"))
        story.append(self._sql_box(report_data.get('sql_used', 'No SQL used.')))
        story.append(Spacer(1, 8))
        story.append(Paragraph(f"<i>{report_data.get('sql_explanation', '')}</i>", ParagraphStyle('I', fontName='Helvetica-Oblique', fontSize=9, textColor=colors.gray)))
        story.append(Spacer(1, 24))
        
        story.extend(self._section_heading("About This Analysis"))
        story.append(Paragraph("This report was generated by a privacy-first 3-agent AI pipeline. Agent 1 clarified intent. Agent 2 generated SQL using only the schema, never the raw data. Agent 3 explained results using only the small result set. The full dataset never left the server.", self.styles['ReportBody']))

        def render_cover(canvas, doc):
            self._cover_page(canvas, doc, "Data Intelligence Report", report_data.get('question', ''), report_data.get('dataset_name', 'Unknown'), report_data.get('row_count', 0))
            
        def render_later_pages(canvas, doc):
            self._add_page_number(canvas, doc)

        doc.build(story, onFirstPage=render_cover, onLaterPages=render_later_pages)
        return buffer.getvalue()

    def generate_dataset_report(self, summary_data: dict) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
        story = []
        
        story.append(Spacer(1, 1))
        story.append(PageBreak())

        # PAGE 2 - OVERVIEW
        story.extend(self._section_heading("Executive Overview"))
        story.append(self._highlight_box(summary_data.get('ai_summary', ''), LIGHT_INDIGO, INDIGO))
        story.append(Spacer(1, 24))
        story.append(self._kpi_grid(summary_data.get('overview', {})))
        story.append(Spacer(1, 12))
        ov = summary_data.get('overview', {})
        story.append(Paragraph(f"<i>Data covers {ov.get('date_range_start', '')} to {ov.get('date_range_end', '')}</i>", ParagraphStyle('I', fontName='Helvetica-Oblique', fontSize=9, textColor=colors.gray)))
        story.append(PageBreak())

        # PAGE 3 - REGIONAL BREAKDOWN
        story.extend(self._section_heading("Revenue by Region"))
        rg = summary_data.get('by_region', [])
        if rg:
            headers = ["Region", "Revenue", "Orders", "Share %"]
            rows = []
            for r in rg:
                rows.append([str(r.get('region')), self._format_currency(r.get('revenue')), f"{r.get('orders'):,}", f"{r.get('share_pct')}%"])
            t = self._data_table(headers, rows)
            
            # Highlight top region (index 1 because of header)
            style = t._argW[0] # This is a hacky way in Platypus but supported.
            # Instead of messing with inner styles, let's just create the style list explicitly.
            bg_style = t._argW[2] # No wait, standard way is: t.setStyle
            t.setStyle(TableStyle([('BACKGROUND', (0,1), (-1,1), LIGHT_GREEN)]))
            
            story.append(t)
            story.append(Spacer(1, 8))
            story.append(Paragraph(f"<b>Top Performing Region: {summary_data.get('top_performers', {}).get('top_region', '')}</b>", self.styles['ReportBody']))
            
        story.append(Spacer(1, 16))
        
        story.extend(self._section_heading("Revenue by Channel"))
        ch = summary_data.get('by_channel', [])
        if ch:
            headers = ["Channel", "Revenue", "Orders"]
            rows = []
            for c in ch:
                rows.append([str(c.get('channel')), self._format_currency(c.get('revenue')), f"{c.get('orders'):,}"])
            story.append(self._data_table(headers, rows))
            
        story.append(Spacer(1, 16))
        
        story.extend(self._section_heading("Revenue by Product"))
        pd = summary_data.get('by_product', [])
        if pd:
            headers = ["Product", "Revenue", "Units Sold", "Share %"]
            rows = []
            for p in pd:
                rows.append([str(p.get('product')), self._format_currency(p.get('revenue')), f"{p.get('units_sold'):,}", f"{p.get('share_pct')}%"])
            pt = self._data_table(headers, rows)
            pt.setStyle(TableStyle([('BACKGROUND', (0,1), (-1,1), LIGHT_GREEN)]))
            story.append(pt)
            
        story.append(PageBreak())

        # PAGE 4 - MONTHLY TREND
        story.extend(self._section_heading("Monthly Revenue Trend (2024)"))
        mt = summary_data.get('monthly_trend', [])
        if mt:
            headers = ["Month", "Revenue", "Orders", "vs Previous Month"]
            rows = []
            prev_rev = None
            max_rev = -1
            min_rev = float('inf')
            max_idx = -1
            min_idx = -1
            
            for i, m in enumerate(mt):
                rev = float(m.get('revenue', 0))
                if rev > max_rev:
                    max_rev = rev
                    max_idx = i
                if rev < min_rev:
                    min_rev = rev
                    min_idx = i
                    
                pct_str = self._format_pct_change(rev, prev_rev) if prev_rev is not None else "—"
                rows.append([str(m.get('month')), self._format_currency(m.get('revenue')), f"{m.get('orders'):,}", Paragraph(pct_str, self.styles['ReportBody'])])
                prev_rev = rev
                
            m_tab = self._data_table(headers, rows)
            
            # Apply highlights
            # rows index + 1 for header offset
            if max_idx >= 0:
                m_tab.setStyle(TableStyle([('BACKGROUND', (0,max_idx+1), (-1,max_idx+1), LIGHT_GREEN)]))
            if min_idx >= 0:
                m_tab.setStyle(TableStyle([('BACKGROUND', (0,min_idx+1), (-1,min_idx+1), LIGHT_RED)]))
            
            story.append(m_tab)
            story.append(Spacer(1, 8))
            tp = summary_data.get('top_performers', {})
            story.append(Paragraph(f"<b>Best Month: {tp.get('best_month', '')} · Worst Month: {tp.get('worst_month', '')}</b>", self.styles['ReportBody']))
            
        story.append(PageBreak())

        # PAGE 5 - PRIVACY & METH
        story.extend(self._section_heading("Data Privacy & Methodology"))
        blocked = summary_data.get('blocked_columns', [])
        if blocked:
            b_text = f"The following sensitive columns were automatically detected and removed before any AI processing: {', '.join(blocked)}<br/><br/>Raw data never left the server at any point."
        else:
            b_text = "No sensitive columns were detected. Raw data never left the server at any point."
        
        story.append(self._highlight_box(b_text, LIGHT_RED, RED))
        story.append(Spacer(1, 24))
        
        story.extend(self._section_heading("How This Report Was Generated"))
        list_style = ParagraphStyle('L', fontName='Helvetica', fontSize=10, leading=14, leftIndent=20)
        items = [
            "1. CSV uploaded and immediately filtered for sensitive columns",
            "2. Filtered data loaded into an in-memory database (never written to disk)",
            "3. 10+ automated SQL queries executed to extract all metrics in this report",
            "4. AI summarized findings in plain English",
            "5. Report compiled and delivered — original data discarded from memory"
        ]
        for it in items:
            story.append(Paragraph(it, list_style))
            story.append(Spacer(1, 4))
            
        story.append(Spacer(1, 16))
        story.extend(self._section_heading("Metric Definitions"))
        
        m_headers = ["Metric", "Description"]
        m_rows = [
            ["Revenue", "Sum of completed transaction amounts"],
            ["Orders", "Total count of all order records"],
            ["Refund Rate", "Percentage of orders with refunded status"],
            ["Avg Order Value", "Mean value of completed transactions"],
            ["Units Sold", "Total quantity of items across all orders"]
        ]
        
        story.append(self._data_table(m_headers, m_rows))
        
        def render_ds_cover(canvas, doc):
            self._cover_page(canvas, doc, "Dataset Intelligence Report", summary_data.get('dataset_name', 'Dataset'), summary_data.get('dataset_name', ''), summary_data.get('row_count', 0), tagline="Comprehensive AI-powered analysis of your sales data")
            
        def render_later_ds_pages(canvas, doc):
            self._add_page_number(canvas, doc)
            
        doc.build(story, onFirstPage=render_ds_cover, onLaterPages=render_later_ds_pages)
        return buffer.getvalue()

pdf_generator = PDFGenerator()
